-- ============================================================================
-- Fase 1: partidas oficiais pós-T0 coletadas da API-Football.
--
-- POR QUE A COLETA É POR DATA, E NÃO POR TIME OU POR LIGA:
-- o plano gratuito responde "Free plans do not have access to this season, try
-- from 2022 to 2024" para QUALQUER consulta com ?season= — o que inclui
-- /teams?league=X&season=2026 e /fixtures?league=X&season=2026. A consulta por
-- data (/fixtures?date=YYYY-MM-DD) não tem essa trava: devolveu 965 jogos do
-- mundo inteiro em 01/08/2026, sem erro.
--
-- Ou seja, consultar por data não é apenas 40× mais econômico que consultar
-- clube a clube: é a única forma que funciona sem plano pago.
--
-- LIMITE QUE ISSO IMPÕE: a janela do plano gratuito é de ~3 dias (ontem, hoje,
-- amanhã). Não existe backfill — jogo cuja janela passou sem sincronizar está
-- perdido para sempre. Daí a rotina rodar 2×/dia e sempre reprocessar ontem.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.club_competition_weights (
  provider     TEXT NOT NULL DEFAULT 'api_football',
  league_id    BIGINT NOT NULL,
  league_name  TEXT NOT NULL,
  categoria    TEXT NOT NULL,
  model_weight NUMERIC(4,2) NOT NULL CHECK (model_weight >= 0 AND model_weight <= 1),
  active       BOOLEAN NOT NULL DEFAULT true,
  PRIMARY KEY (provider, league_id)
);

-- IDs conferidos contra /leagues da própria API-Football em 01/08/2026.
INSERT INTO public.club_competition_weights (league_id, league_name, categoria, model_weight) VALUES
  (13,  'CONMEBOL Libertadores',        'continental',       1.00),
  (11,  'CONMEBOL Sudamericana',        'continental',       1.00),
  (73,  'Copa Do Brasil',               'copa_nacional',     1.00),
  (130, 'Copa Argentina',               'copa_nacional',     1.00),
  (267, 'Copa Chile',                   'copa_nacional',     1.00),
  (241, 'Copa Colombia',                'copa_nacional',     1.00),
  (71,  'Brasileirao Serie A',          'primeira_divisao',  1.00),
  (128, 'Liga Profesional Argentina',   'primeira_divisao',  1.00),
  (265, 'Chile Primera Division',       'primeira_divisao',  1.00),
  (239, 'Colombia Primera A',           'primeira_divisao',  1.00),
  (242, 'Ecuador Liga Pro',             'primeira_divisao',  1.00),
  (281, 'Peru Primera Division',        'primeira_divisao',  1.00),
  (268, 'Uruguay Primera Division',     'primeira_divisao',  1.00),
  (250, 'Paraguay Div Prof Apertura',   'primeira_divisao',  1.00),
  (252, 'Paraguay Div Prof Clausura',   'primeira_divisao',  1.00),
  (344, 'Bolivia Primera Division',     'primeira_divisao',  1.00),
  (72,  'Brasileirao Serie B',          'segunda_divisao',   0.80),
  (129, 'Primera Nacional',             'segunda_divisao',   0.80),
  (266, 'Chile Primera B',              'segunda_divisao',   0.80),
  (240, 'Colombia Primera B',           'segunda_divisao',   0.80),
  (243, 'Ecuador Liga Pro Serie B',     'segunda_divisao',   0.80),
  (282, 'Peru Segunda Division',        'segunda_divisao',   0.80),
  (269, 'Uruguay Segunda Division',     'segunda_divisao',   0.80),
  (251, 'Paraguay Division Intermedia', 'segunda_divisao',   0.80),
  (75,  'Brasileirao Serie C',          'segunda_divisao',   0.80),
  -- Estaduais valem menos: é onde a rotação de elenco mais distorce a leitura
  -- de força, e é a competição que a especificação já sugeria com 0,60.
  (475, 'Paulista A1',       'estadual', 0.60), (624, 'Carioca 1',       'estadual', 0.60),
  (629, 'Mineiro 1',         'estadual', 0.60), (477, 'Gaucho 1',        'estadual', 0.60),
  (604, 'Catarinense 1',     'estadual', 0.60), (606, 'Paranaense 1',    'estadual', 0.60),
  (602, 'Baiano 1',          'estadual', 0.60), (622, 'Pernambucano 1',  'estadual', 0.60),
  (609, 'Cearense 1',        'estadual', 0.60), (628, 'Goiano 1',        'estadual', 0.60),
  (627, 'Paraense',          'estadual', 0.60), (612, 'Copa do Nordeste','estadual', 0.60),
  -- Amistoso não move o modelo, mas a partida continua sendo guardada e exibida.
  (667, 'Club Friendlies',   'amistoso', 0.00)
ON CONFLICT (provider, league_id) DO NOTHING;

ALTER TABLE public.club_competition_weights ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Pesos visiveis para todos" ON public.club_competition_weights FOR SELECT USING (true);
CREATE POLICY "Admins gerenciam pesos" ON public.club_competition_weights FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_admin = true));

CREATE TABLE IF NOT EXISTS public.club_fixtures (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider            TEXT   NOT NULL DEFAULT 'api_football',
  provider_fixture_id BIGINT NOT NULL,
  league_id           BIGINT,
  league_name         TEXT,
  round_name          TEXT,
  kickoff_at          TIMESTAMPTZ NOT NULL,
  status              TEXT NOT NULL,
  home_team_key       TEXT REFERENCES public.club_source_ids(team_key) ON UPDATE CASCADE,
  away_team_key       TEXT REFERENCES public.club_source_ids(team_key) ON UPDATE CASCADE,
  home_provider_id    BIGINT NOT NULL,
  away_provider_id    BIGINT NOT NULL,
  home_team_name      TEXT NOT NULL,
  away_team_name      TEXT NOT NULL,
  -- 90 minutos SEPARADO de prorrogação e pênaltis. A API devolve `goals` já
  -- somando a prorrogação; o tempo regulamentar puro está em score.fulltime.
  -- Misturar os dois inflaria o ataque de quem venceu na prorrogação (§6.9).
  goals_home_90       INTEGER,
  goals_away_90       INTEGER,
  goals_home_extra    INTEGER,
  goals_away_extra    INTEGER,
  penalties_home      INTEGER,
  penalties_away      INTEGER,
  venue_name          TEXT,
  model_eligible      BOOLEAN NOT NULL DEFAULT false,
  model_exclusion_reason TEXT,
  synced_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (provider, provider_fixture_id)
);

CREATE INDEX IF NOT EXISTS club_fixtures_kickoff_idx  ON public.club_fixtures (kickoff_at DESC);
CREATE INDEX IF NOT EXISTS club_fixtures_home_idx     ON public.club_fixtures (home_team_key, kickoff_at DESC);
CREATE INDEX IF NOT EXISTS club_fixtures_away_idx     ON public.club_fixtures (away_team_key, kickoff_at DESC);
CREATE INDEX IF NOT EXISTS club_fixtures_elegivel_idx ON public.club_fixtures (model_eligible, kickoff_at DESC);

ALTER TABLE public.club_fixtures ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Jogos dos clubes visiveis para todos" ON public.club_fixtures FOR SELECT USING (true);
CREATE POLICY "Admins gerenciam jogos dos clubes" ON public.club_fixtures FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_admin = true));

CREATE TABLE IF NOT EXISTS public.club_sync_log (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at    TIMESTAMPTZ,
  target_date    DATE,
  status         TEXT NOT NULL DEFAULT 'running',
  fixtures_seen  INTEGER,
  fixtures_kept  INTEGER,
  requests_used  INTEGER,
  unmapped_teams TEXT[],
  error_message  TEXT
);
ALTER TABLE public.club_sync_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins leem o log de sync" ON public.club_sync_log FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_admin = true));
