-- ============================================================================
-- Fundação do modelo de probabilidade do bolão de clubes (Fase 0)
--
-- Cria as tabelas de referência: snapshot Opta congelado, mapa canônico de
-- clubes e apelidos. NÃO cria nada de partidas externas nem de força calculada
-- — isso vem na Fase 1, depois de fixado o fornecedor de dados.
--
-- Ver MODELO_CLUBES_PLANO.md.
-- ============================================================================

-- ── Normalização de nome de clube ───────────────────────────────────────────
-- translate() em vez de unaccent(): unaccent é STABLE (depende do dicionário
-- carregado), o que impede usá-la em índice. translate() é genuinamente
-- IMMUTABLE e não exige extensão. Espelha teamKey() do lado TypeScript.
CREATE OR REPLACE FUNCTION public.club_key_normalize(p_nome TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
  SELECT NULLIF(
    btrim(
      regexp_replace(
        translate(
          lower(COALESCE(p_nome, '')),
          'áàâãäéèêëíìîïóòôõöúùûüçñý',
          'aaaaaeeeeiiiiooooouuuucny'
        ),
        '[^a-z0-9]+', ' ', 'g'
      )
    ),
    ''
  );
$$;

COMMENT ON FUNCTION public.club_key_normalize(TEXT) IS
  'Nome de clube -> forma canônica comparável (minúsculo, sem acento, separadores colapsados).';

-- ── Snapshot Opta ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.opta_snapshots (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  snapshot_at  DATE NOT NULL,
  source_file  TEXT NOT NULL,
  total_clubs  INTEGER NOT NULL CHECK (total_clubs > 0),
  is_active    BOOLEAN NOT NULL DEFAULT false,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- No máximo um snapshot ativo. O índice parcial é o que garante isso de fato;
-- deixar como convenção documentada não seguraria.
CREATE UNIQUE INDEX IF NOT EXISTS opta_snapshots_um_ativo
  ON public.opta_snapshots (is_active) WHERE is_active;

CREATE TABLE IF NOT EXISTS public.opta_club_ratings (
  snapshot_id           UUID NOT NULL REFERENCES public.opta_snapshots(id) ON DELETE CASCADE,
  opta_contestant_id    TEXT NOT NULL,
  opta_numeric_id       TEXT,
  team_name             TEXT NOT NULL,
  club_name             TEXT,
  country               TEXT,
  confederation         TEXT,
  domestic_league_id    TEXT,
  domestic_league_name  TEXT,
  -- 0–100 com muitas casas (ex.: 94.7060589471). numeric(9,6) preserva o
  -- suficiente; a 7ª casa não muda nada num modelo cujo beta é ~0,036.
  rating                NUMERIC(9,6) NOT NULL,
  global_rank           INTEGER,
  confederation_rank    INTEGER,
  last_week_rating      NUMERIC(9,6),
  PRIMARY KEY (snapshot_id, opta_contestant_id)
);

CREATE INDEX IF NOT EXISTS opta_club_ratings_nome_idx
  ON public.opta_club_ratings (public.club_key_normalize(team_name));
CREATE INDEX IF NOT EXISTS opta_club_ratings_pais_idx
  ON public.opta_club_ratings (country);

-- ── Mapa canônico de clubes ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.club_source_ids (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_key             TEXT NOT NULL UNIQUE,
  canonical_name       TEXT NOT NULL,
  country              TEXT,
  opta_contestant_id   TEXT,
  -- Os dois fornecedores em colunas separadas: ainda não está decidido qual
  -- será usado, e manter os dois permite trocar sem migração de dados.
  sportmonks_team_id   BIGINT,
  api_football_team_id BIGINT,
  is_bolao_team        BOOLEAN NOT NULL DEFAULT false,
  active               BOOLEAN NOT NULL DEFAULT true,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT club_source_ids_team_key_canonico
    CHECK (team_key = public.club_key_normalize(team_key))
);

CREATE UNIQUE INDEX IF NOT EXISTS club_source_ids_opta_idx
  ON public.club_source_ids (opta_contestant_id) WHERE opta_contestant_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS club_source_ids_sportmonks_idx
  ON public.club_source_ids (sportmonks_team_id) WHERE sportmonks_team_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS club_source_ids_apifootball_idx
  ON public.club_source_ids (api_football_team_id) WHERE api_football_team_id IS NOT NULL;

-- ── Apelidos ────────────────────────────────────────────────────────────────
-- O mesmo clube aparece com nomes diferentes em cada fonte — e, no nosso caso,
-- dentro da própria tabela matches ("Vasco" na Copa do Brasil e "Vasco da Gama"
-- na Sul-Americana; "Bragantino" e "Red Bull Bragantino" no Paulistão). Sem
-- esta tabela o mesmo clube vira dois.
CREATE TABLE IF NOT EXISTS public.club_aliases (
  alias      TEXT PRIMARY KEY,
  team_key   TEXT NOT NULL REFERENCES public.club_source_ids(team_key) ON UPDATE CASCADE ON DELETE CASCADE,
  origem     TEXT NOT NULL CHECK (origem IN ('app_matches', 'opta', 'provider', 'manual')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT club_aliases_alias_canonico
    CHECK (alias = public.club_key_normalize(alias))
);

CREATE INDEX IF NOT EXISTS club_aliases_team_key_idx ON public.club_aliases (team_key);

-- Resolve um nome livre para o team_key canônico. Tenta, nesta ordem:
-- 1) apelido cadastrado; 2) o próprio team_key; 3) nada (NULL — nunca chuta).
CREATE OR REPLACE FUNCTION public.club_resolve(p_nome TEXT)
RETURNS TEXT
LANGUAGE sql
STABLE
AS $$
  SELECT COALESCE(
    (SELECT a.team_key FROM public.club_aliases a
      WHERE a.alias = public.club_key_normalize(p_nome)),
    (SELECT c.team_key FROM public.club_source_ids c
      WHERE c.team_key = public.club_key_normalize(p_nome))
  );
$$;

COMMENT ON FUNCTION public.club_resolve(TEXT) IS
  'Nome livre -> team_key canônico, ou NULL quando não há correspondência segura.';

-- ── Em quais competições cada clube está ────────────────────────────────────
-- is_bolao_team booleano não diz de QUAL competição o clube participa, e 7 dos
-- 40 clubes estão em duas. Vista derivada de matches: não duplica dado e não
-- sai do ar quando o admin corrige uma chave.
-- security_invoker: a vista respeita a RLS de quem consulta, em vez de rodar
-- com os privilégios do dono. Aqui as tabelas de baixo são públicas de leitura,
-- então não muda o resultado — mas evita que a vista vire um furo se algum dia
-- alguma delas for fechada.
CREATE OR REPLACE VIEW public.club_bolao_entries
WITH (security_invoker = true) AS
SELECT DISTINCT
  t.slug        AS tournament_slug,
  m.competition,
  public.club_resolve(nome) AS team_key,
  nome          AS nome_no_app
FROM public.matches m
JOIN public.tournaments t ON t.id = m.tournament_id
CROSS JOIN LATERAL (VALUES (m.team_home), (m.team_away)) AS v(nome)
WHERE m.competition IS NOT NULL;

-- ── RLS ─────────────────────────────────────────────────────────────────────
ALTER TABLE public.opta_snapshots    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.opta_club_ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.club_source_ids   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.club_aliases      ENABLE ROW LEVEL SECURITY;

-- opta_snapshots / opta_club_ratings: RLS ligada e NENHUMA policy de leitura.
-- É deliberado. São 13.789 linhas de um dataset licenciado que nada na
-- interface precisa: o motor lê server-side (service role / pg_cron) e publica
-- só o resultado derivado. Sem policy, a Data API não devolve nada.
CREATE POLICY "Admins gerenciam snapshots Opta" ON public.opta_snapshots
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_admin = true)
  );
CREATE POLICY "Admins gerenciam ratings Opta" ON public.opta_club_ratings
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_admin = true)
  );

-- club_source_ids / club_aliases: dado de referência, mesma convenção de
-- matches e ties — todo mundo lê, só admin escreve.
CREATE POLICY "Clubes visíveis para todos" ON public.club_source_ids
  FOR SELECT USING (true);
CREATE POLICY "Admins gerenciam clubes" ON public.club_source_ids
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_admin = true)
  );

CREATE POLICY "Apelidos visíveis para todos" ON public.club_aliases
  FOR SELECT USING (true);
CREATE POLICY "Admins gerenciam apelidos" ON public.club_aliases
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_admin = true)
  );
