-- ============================================================================
-- Lançamento automático do resultado, com trava graduada pelo que é reversível.
-- ============================================================================
-- Até aqui o placar sugerido esperava um clique. O receio que justificava o
-- clique era lançar jogo errado por pareamento errado — e esse risco deixou de
-- existir quando a identidade passou a ser o id do provedor (migrações 000001
-- e 000004). O que sobra não é sobre identidade:
--
--   • um placar lançado pontua na hora, e desfazer é visível a todos;
--   • a perna que decide o confronto AVANÇA O CHAVEAMENTO — grava vencedor,
--     cria os jogos da fase seguinte e, na final, o campeão. E `ensure_tie_
--     matches` RECUSA corrigir uma fase que já recebeu palpite. Esse é o único
--     passo do fluxo que não se desfaz.
--
-- Daí a trava ser graduada, e não uniforme:
--
--   IDA (ou perna que não decide) -> lança na hora. É reversível: o motor
--     devolve os pontos ao reabrir e nada mais se move.
--   PERNA QUE DECIDE -> exige carência de 15 min desde que a partida apareceu
--     encerrada (com a varredura de 20 em 20 min, é a varredura seguinte) E que
--     a OUTRA perna já esteja lançada e batendo com a API.
--   FINAL -> nunca. Decisão de projeto: define campeão e dispara a pontuação de
--     pódio, é um jogo por competição, e o automático renderia quase nada.
--
-- SOBRE "ESPERAR DUAS VARREDURAS PARA TODOS": descartado. O risco nunca foi a
-- API mandar placar errado — é o payload estar pela metade no instante em que o
-- status vira FT. Isso se checa na hora, sem esperar: minuto de jogo, placar
-- dos 90 preenchido e coerência dos pênaltis. Custa zero e pega o caso real.
--
-- Nada disso substitui a aba do admin: tudo que for retido continua lá, com o
-- motivo escrito.
-- ============================================================================

-- ── Interruptor, por torneio ────────────────────────────────────────────────
-- No banco de propósito: desligar não pode depender de deploy.
ALTER TABLE public.tournaments
  ADD COLUMN IF NOT EXISTS auto_resultado BOOLEAN NOT NULL DEFAULT false;

COMMENT ON COLUMN public.tournaments.auto_resultado IS
  'Lança sozinho o resultado que a API confirma, com as travas de auto_lancar_resultados(). A final nunca entra.';

-- ── Trilha ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.resultado_automatico_log (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id            INTEGER NOT NULL,
  provider_fixture_id BIGINT,
  score_home          INTEGER,
  score_away          INTEGER,
  pen_winner          TEXT,
  avanco              JSONB,
  aplicado_em         TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.resultado_automatico_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins leem o log de lancamento automatico" ON public.resultado_automatico_log;
CREATE POLICY "Admins leem o log de lancamento automatico"
  ON public.resultado_automatico_log FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.is_admin = true));

COMMENT ON TABLE public.resultado_automatico_log IS
  'Uma linha por resultado lançado sem clique humano, com o que a API dizia e o que o chaveamento fez em seguida.';

-- ── O motor ─────────────────────────────────────────────────────────────────
-- `p_simular` roda a mesma decisão SEM gravar nada e ignorando o interruptor:
-- é o modo sombra, para conferir por alguns dias se a máquina decidiria igual
-- ao humano antes de entregar o volante a ela.
CREATE OR REPLACE FUNCTION public.auto_lancar_resultados(p_simular BOOLEAN DEFAULT false)
RETURNS TABLE (out_match_id INTEGER, out_acao TEXT, out_detalhe TEXT)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $function$
DECLARE
  t        RECORD;
  s        RECORD;
  m        public.matches%ROWTYPE;
  f        public.club_fixtures%ROWTYPE;
  ti       public.ties%ROWTYPE;
  irma     public.matches%ROWTYPE;
  v_decide BOOLEAN;
  v_irma_ok BOOLEAN;
  v_agreg_a INTEGER; v_agreg_b INTEGER;
  v_motivo TEXT;
  v_avanco JSONB;
BEGIN
  FOR t IN SELECT tr.id FROM public.tournaments tr WHERE tr.auto_resultado OR p_simular LOOP
    FOR s IN
      -- Ordem de data: a ida precisa estar lançada antes da volta, senão o
      -- gate de pênaltis (tie_aggregate_tied) zera os pontos da volta e não
      -- volta atrás sozinho.
      SELECT * FROM public.resultados_sugeridos(t.id) r
       WHERE r.status <> 'FINISHED'
       ORDER BY r.match_date
    LOOP
      v_motivo := NULL;
      v_avanco := NULL;

      SELECT * INTO m  FROM public.matches       WHERE id = s.match_id::INTEGER;
      SELECT * INTO f  FROM public.club_fixtures WHERE provider_fixture_id = s.provider_fixture_id;
      ti := NULL;
      IF m.tie_id IS NOT NULL THEN
        SELECT * INTO ti FROM public.ties WHERE id = m.tie_id;
      END IF;

      -- Esta perna DECIDE o confronto? É ela que avança o chaveamento.
      v_decide := (ti.id IS NOT NULL AND (
                     (ti.series_type = 'two_leg' AND m.leg = 'volta')
                  OR (ti.series_type = 'single')));

      -- ---- Travas ----------------------------------------------------------
      IF ti.round = 'final' THEN
        v_motivo := 'final: lançamento manual, por decisão de projeto';

      -- Divergência de cadastro: quero olho humano, não é erro da API.
      ELSIF s.invertido THEN
        v_motivo := 'mando invertido em relação ao nosso cadastro';

      -- Este bolão pontua os 90 minutos; prorrogação real muda a leitura do
      -- confronto e merece conferência.
      ELSIF s.teve_prorrogacao THEN
        v_motivo := 'a partida teve prorrogação';

      -- ---- Payload pela metade (checagem instantânea, sem espera) ----------
      ELSIF f.goals_home_90 IS NULL OR f.goals_away_90 IS NULL THEN
        v_motivo := 'placar dos 90 minutos ausente na fonte';

      ELSIF f.status = 'FT' AND COALESCE(f.elapsed, 90) < 90 THEN
        v_motivo := format('fonte marcou encerrado com %s minutos', f.elapsed);

      -- Pênalti em jogo que não foi a pênaltis: algo não fecha.
      ELSIF s.sug_pen_winner IS NOT NULL AND m.leg = 'ida' THEN
        v_motivo := 'a fonte trouxe pênaltis num jogo de ida';

      ELSIF s.sug_pen_winner IS NOT NULL AND ti.series_type = 'single'
            AND f.goals_home_90 <> f.goals_away_90 THEN
        v_motivo := 'pênaltis num jogo único que não terminou empatado';

      -- ---- Trava da perna que decide --------------------------------------
      ELSIF v_decide AND f.finalizado_visto_em IS NULL THEN
        v_motivo := 'sem instante de encerramento registrado';

      ELSIF v_decide AND f.finalizado_visto_em > now() - interval '15 minutes' THEN
        v_motivo := 'aguardando a varredura de confirmação (perna que decide o confronto)';

      END IF;

      -- Confronto de ida e volta: a outra perna precisa estar lançada E bater
      -- com a API. É a conferência por dois caminhos: o agregado que o
      -- chaveamento vai usar (de `matches`) tem de coincidir com o que a fonte
      -- registrou (de `club_fixtures`).
      IF v_motivo IS NULL AND v_decide AND ti.series_type = 'two_leg' THEN
        SELECT * INTO irma FROM public.matches WHERE id = ti.ida_match_id;
        IF irma.id IS NULL OR irma.status <> 'FINISHED' THEN
          v_motivo := 'o jogo de ida ainda não foi lançado';
        ELSE
          SELECT NOT COALESCE(r.divergente, TRUE) INTO v_irma_ok
            FROM public.resultados_sugeridos(t.id) r WHERE r.match_id = irma.id;
          IF NOT COALESCE(v_irma_ok, FALSE) THEN
            v_motivo := 'o placar da ida não confere com o da fonte';
          END IF;
        END IF;
      END IF;

      -- Agregado empatado exige vencedor dos pênaltis, senão o classificado
      -- fica indefinido e o chaveamento trava no meio.
      IF v_motivo IS NULL AND v_decide AND ti.series_type = 'two_leg' THEN
        v_agreg_a := (CASE WHEN irma.team_home = ti.team_a THEN irma.score_home ELSE irma.score_away END)
                   + (CASE WHEN m.team_home    = ti.team_a THEN s.sug_home      ELSE s.sug_away      END);
        v_agreg_b := (CASE WHEN irma.team_home = ti.team_b THEN irma.score_home ELSE irma.score_away END)
                   + (CASE WHEN m.team_home    = ti.team_b THEN s.sug_home      ELSE s.sug_away      END);
        IF v_agreg_a = v_agreg_b AND s.sug_pen_winner IS NULL THEN
          v_motivo := 'agregado empatado e a fonte não trouxe o vencedor dos pênaltis';
        END IF;
      END IF;

      -- ---- Ação ------------------------------------------------------------
      IF v_motivo IS NOT NULL THEN
        out_match_id := m.id; out_acao := 'retido'; out_detalhe := v_motivo;
        RETURN NEXT;
        CONTINUE;
      END IF;

      IF p_simular THEN
        out_match_id := m.id;
        out_acao     := 'lancaria';
        out_detalhe  := format('%s %s x %s %s', m.team_home, s.sug_home, s.sug_away, m.team_away)
                        || COALESCE(' · pênaltis: ' || s.sug_pen_winner, '');
        RETURN NEXT;
        CONTINUE;
      END IF;

      UPDATE public.matches
         SET score_home        = s.sug_home,
             score_away        = s.sug_away,
             status            = 'FINISHED',
             extra_time_result = CASE WHEN m.is_knockout THEN NULL ELSE m.extra_time_result END,
             pen_home          = CASE WHEN m.is_knockout THEN NULL ELSE m.pen_home END,
             pen_away          = CASE WHEN m.is_knockout THEN NULL ELSE m.pen_away END,
             pen_winner        = CASE WHEN m.is_knockout THEN s.sug_pen_winner ELSE m.pen_winner END
       WHERE id = m.id;

      -- Chaveamento em bloco próprio: se ele recusar avançar (fase seguinte já
      -- com palpite, por exemplo), o placar e os pontos FICAM — só o avanço é
      -- que espera o admin.
      IF m.tie_id IS NOT NULL THEN
        BEGIN
          v_avanco := public.advance_tie(m.tie_id);
        EXCEPTION WHEN OTHERS THEN
          v_avanco := jsonb_build_object('advanced', false, 'warning', SQLERRM);
        END;
      END IF;

      INSERT INTO public.resultado_automatico_log
        (match_id, provider_fixture_id, score_home, score_away, pen_winner, avanco)
      VALUES (m.id, s.provider_fixture_id, s.sug_home, s.sug_away, s.sug_pen_winner, v_avanco);

      out_match_id := m.id;
      out_acao     := 'lancado';
      out_detalhe  := format('%s %s x %s %s', m.team_home, s.sug_home, s.sug_away, m.team_away)
                      || COALESCE(' · ' || (v_avanco->>'info'), '')
                      || COALESCE(' · aviso: ' || (v_avanco->>'warning'), '');
      RETURN NEXT;
    END LOOP;
  END LOOP;
END;
$function$;

REVOKE ALL ON FUNCTION public.auto_lancar_resultados(BOOLEAN) FROM PUBLIC, anon, authenticated;

COMMENT ON FUNCTION public.auto_lancar_resultados(BOOLEAN) IS
  'Lança sozinho o resultado que a API confirma, nos torneios com auto_resultado. Ida na hora; perna que decide só após carência e com a outra perna conferida; final nunca. p_simular = decide sem gravar, ignorando o interruptor.';

-- ── Chamada ao fim de cada varredura ────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.sync_club_fixtures_recent(p_incluir_amanha boolean DEFAULT false)
RETURNS TABLE(dia date, vistos integer, guardados integer, erro text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $function$
DECLARE d DATE; r RECORD; hoje_utc DATE; dias DATE[];
BEGIN
  hoje_utc := (now() AT TIME ZONE 'utc')::date;
  dias := ARRAY[hoje_utc];

  IF EXISTS (
    SELECT 1 FROM public.club_fixtures f
     WHERE (f.kickoff_at AT TIME ZONE 'utc')::date = hoje_utc - 1
       AND f.status NOT IN ('FT','AET','PEN','PST','CANC','ABD','AWD','WO')
       AND f.kickoff_at > now() - interval '12 hours'
  ) THEN
    dias := ARRAY[hoje_utc - 1] || dias;
  END IF;

  IF p_incluir_amanha THEN dias := dias || (hoje_utc + 1); END IF;

  FOREACH d IN ARRAY dias
  LOOP
    BEGIN
      SELECT * INTO r FROM public.sync_club_fixtures(d);
      dia := d; vistos := r.vistos; guardados := r.guardados; erro := NULL;
    EXCEPTION WHEN OTHERS THEN
      dia := d; vistos := NULL; guardados := NULL; erro := SQLERRM;
    END;
    RETURN NEXT;
  END LOOP;

  PERFORM public.pin_provider_ids();
  PERFORM public.reresolve_fixture_keys();
  PERFORM public.pin_crest_urls();
  PERFORM public.registra_provider_teams();

  -- Depois da identidade estar resolvida, nunca antes: o auto-lançamento
  -- depende do pareamento, e o pareamento depende da chave.
  BEGIN
    PERFORM public.auto_lancar_resultados();
  EXCEPTION WHEN OTHERS THEN
    -- Um erro aqui não pode derrubar a coleta, que é o que não dá para refazer
    -- depois (a janela do plano gratuito é de 3 dias).
    RAISE WARNING 'auto_lancar_resultados falhou: %', SQLERRM;
  END;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Como ver o que ele FARIA, sem ligar nada (modo sombra):
--   SELECT * FROM public.auto_lancar_resultados(true);
-- Como ligar (por torneio):
--   UPDATE public.tournaments SET auto_resultado = true WHERE slug = '<slug>';
-- Como auditar depois:
--   SELECT * FROM public.resultado_automatico_log ORDER BY aplicado_em DESC;
-- ---------------------------------------------------------------------------
